version: '3.9'

services:
  db:
    ports:
      -   target: 3306
          published: 5333
          protocol: tcp
  nginx:
    ports:
      -   target: 80
          published: 8447
          protocol: tcp
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
