version: '3.9'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: symfony_php_dev
    environment:
      APP_ENV: dev
      DATABASE_TEST_HOST: db_test
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG} # Required for xdebug.ini
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "127.0.0.1:9000"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - db
    volumes:
      - .:/srv/api:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini/:/usr/local/etc/php/conf.d/symfony.ini
      - ./docker/php/conf.d/zz-php-fpm.conf:/usr/local/etc/php-fpm.d/zz-php-fpm.conf:ro
      - ./docker/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: symfony_nginx_dev
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    cap_add:
      - SYS_NICE
    volumes:
      - db-data:/var/lib/mysql:rw

  db_test:
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-test-data:/var/lib/mysql:rw

  mailer:
    image: sj26/mailcatcher
    ports:
      - target: 1025
        published: 1025
      - target: 1080
        published: 1080

volumes:
  db-data:
  db-test-data:
